# Generated by Django 4.0.5 on 2022-07-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla', '0012_alter_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
